version: '1'
services: 
  course-client:
    build: ./users
    ports:
      - "6001:6001"
    image: cty288/course-client
    

  course-admin:
    build: ./admin
    ports:
      - "7001:7001"
    image: cty288/course-admin